{
 "title": "Home",
 "time": { "from": "2022-11-08T23:00:00.000Z", "to": "2022-11-09T22:59:59.000Z" },
 "panels": [
  {
   "title": "Energy Consumption per Phase (W)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Phase A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "iammeter_meterkast_power_a" }
     ]
    },
    {
     "alias": "Phase B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "iammeter_meterkast_power_b" }
     ]
    },
    {
     "alias": "Phase C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "iammeter_meterkast_power_c" }
     ]
    }
   ]
  },
  {
   "title": "Energy Consumption (W)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expression": "$A+$B+$C", "type": "math" }
   ]
  },
  {
   "title": "Export Energy Phase (KWh)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Export Phase A",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT -spread(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'iammeter_meterkast_exportgrid_a') AND $timeFilter GROUP BY time(15m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "iammeter_meterkast_exportgrid_a"
      }
     ]
    },
    {
     "alias": "Export Phase B",
     "query": "SELECT -spread(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'iammeter_meterkast_exportgrid_b') AND $timeFilter GROUP BY time(15m) fill(null)"
    },
    {
     "alias": "Export Phase C",
     "query": "SELECT -spread(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'iammeter_meterkast_exportgrid_c') AND $timeFilter GROUP BY time(15m) fill(null)"
    }
   ]
  },
  {
   "title": "Import Energy per Phase (Kwh)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Import Phase A",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT spread(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'iammeter_meterkast_importenergy_a') AND $timeFilter GROUP BY time(15m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "iammeter_meterkast_exportgrid_a"
      }
     ]
    },
    {
     "alias": "Import Phase B",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT spread(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'iammeter_meterkast_importenergy_b') AND $timeFilter GROUP BY time(15m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "iammeter_meterkast_exportgrid_a"
      }
     ]
    },
    {
     "alias": "Import Phase C",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT spread(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'iammeter_meterkast_importenergy_c') AND $timeFilter GROUP BY time(15m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "iammeter_meterkast_exportgrid_a"
      }
     ]
    }
   ]
  },
  {
   "title": "Energy Balance (Kwh)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    { "expression": "$A+$B+$C", "type": "math" },
    { "expression": "$D+$E+$F", "type": "math" }
   ]
  }
 ]
}